### ISSUE TITLE
What license do we use?

### ISSUE THREAD

**Issue by QEDK** [notconfusing/WIGI#18]
Currently we use the MIT license.
I say, we use MPL 2.0 instead.
It provides an express grant of patent rights from the contributor to the recipient.
It requires the disclosure of source.
And prevents them from using a trademark (if we have one).
This, I believe this will be an impetus to open-source coding.
If everyone agrees, I can proceed with the change.

**Comment by QEDK** [comment]
@notconfusing @hargup @vivekiitkgp Read the issue.

**Comment by hargup** [comment]
Licenses are generally classified on the basis of how much permission it gives
on the use of code. On this criterion licenses generally fall between the most
permissive BSD license to the least permissive GPL licenses. BSD is practically
public domain and GPL restricts the programmer to release the derivatives with only
the GPL License. BSD is good in the sense that it promotes to be reused in most
possible ways. GPL is good in the sense that it promotes potential users of the
code to "give back" the improvements they make to the code. MPL somewhat falls
in between. On this criterion, I would prefer BSD-like permissive licenses
because we would want other people to develop WIGI like indexes for other
projects.

In terms of permissibility, MIT is equivalent to BSD. If you want patent right
Apache license is also a good choice, but I don't think there is anything we can
or we would want to file a patent for.

Unless you have very strong reasons in favor of MPL, I'm again the change of license to it.

**Comment by QEDK** [comment]
@hargup I already said it:
- Express grant of patent rights.
- Recipients cannot produce work under the WIGI name.
- Our source code must be made available to the end-user.

**Comment by hargup** [comment]
See when you are pitching for one license you cannot completely ignore other licenses. MPL has the characteristics you mentioned and other licenses have different characteristics. So, you have to tell us why the characteristics of MPL are important to us and how do they compare with other licenses.

> - Express grant of patent rights.

WIGI is more like a scientific publication rather than a software package that can be sold. I don't think we really need patent rights also I don't think there will be anything that could be patented or there will be anyone among us who will care enough to file a patent or sue someone using our code.

> - Recipients cannot produce work under the WIGI name

MPL explicitly disallows the use of project trademarks but so does Apache, with GPL we can add an additional clause to decline the right to trademarks. Most of the other Licenses don't explicitly mention trademarks.

> - Our source code must be made available to the end-user.

This also really doesn't matter in our case. We are not really providing a software package for the end user to use, we are just giving an index to the Wikipedia project, so there is no end user. For someone who will use our code will probably be creating their own indexes, hence this clause won't really be evoked. This is somewhat similar to the reason why you don't have to provide source code for the GPLed software running on a server. See [AGPL](https://www.gnu.org/licenses/why-affero-gpl.html). Plus such clauses will only add to the confusion in understanding the terms and it can discouraging to the other programmer, therefore I would like to go with a simple "do whatever you like" type license. In this sense, the current MIT license is a good choice.

**Comment by QEDK** [comment]
You don't get it. 
Making it simple and permissive isn't about it.
It's about sharing improvements.

> Express grant of patent rights.

It's not us possessing patent rights, it's allowing patent submitters to use our content. MIT doesn't state this.

> Recipients cannot produce work under the WIGI name

MIT doesn't allow this and GPL has certain restrictions like "Sublicensing" and "State changes".

> Our source code must be made available to the end-user.

Why not? MIT doesn't state this either. This would make sure that end-users have easy access to our code. And in the hands of some good dev, there would surely be improvements.

I've asked for your opinion and you've given that to me. Thank you for that.

**Comment by hargup** [comment]
The clause that enforces distributors/vendors of software to provide the source
code is important only when our code is redistributed/reused by someone outside
the project. Because we can always give the source code to people regardless of
the license of the software, and currently we are doing it. In my previous
comment I explained why it might be _theoretically_ hard to enforce this clause.
Practical enforcements can be much much harder.

Now, you are making it sound like that MPL is the only good open source license.
But my point is there are a lot of open source licenses and they have their own
pros and cons depending on where you are using it. You can find very successful
projects with every major license, like Python in BSD, Linux in GPL, Firefox in
MPL, Ruby on Rails in MIT and Android OS in Apache. Different projects choose to
have different licenses due to different reasons. When you are comparing
licenses do it in the context of project, because there is no one, "right"
license. So, when you say MPL is good because it permits patent grants then
explain why patents are important to **us**. If you say simplicity and
permittivity of the license are not important, then explain **why** they are not
important for **us**.

I also feel that licensing issues are not very important for us at this stage
and discussing it is [bikeshedding](http://bikeshed.com/). I won't comment
further on the thread and I take @notconfusing 's decision as final.

**Comment by QEDK** [comment]
This isn't such a grave issue.
All I'm saying is MIT doesn't require modifications be open sourced whereas the MPL does. If improvements are open, isn't it a win-win for everyone?
MPL includes everything MIT does with 3 additional points, 1 of them being a benefit to the recipient while the other 2 being benefits to us.

**Comment by fsoong** [comment]
I think Masssly (for some reason, I am unable to tag him on any comments I write on Github) brought up a good point about who will maintain our project after we'd done with it. I'm wondering if that'll impact what kind of license we'd want to use.

**Comment by notconfusing** [comment]
For this particular project, because we don't have a long term contract for future support we should do our best to make sure our code is used. Because MIT is more Open, it means it will be more attractive to use. I'm pretty happy if someone decides to use our code but doesn't open source their modification. The purpose of this grant is data-use, and MIT achieves that best in my opinion.

**Comment by raivivek** [comment]
I guess this can be closed for the time being. If anyone, however, still disagrees then feel free to reopen it.
