### ISSUE TITLE
Submit an infographic to Wikidata Visualisation Challenge if Time

### ISSUE THREAD

**Issue by notconfusing** [notconfusing/WIGI#19]
https://se.wikimedia.org/wiki/Projekt:%C3%96ppna_data_2015/Visualisering/T%C3%A4vling

What

```
Data from, or about, Wikidata must be included in the visualization.
Visualizations that combine this with other Open Data sources are encouraged by the jury.
It is allowed to reuse resources produced before the competition starts, i.e. you do not have to start from scratch.
```

May 4, 09.00 - June 1, 23:59 (CEST)

**Comment by fsoong** [comment]
oh dear

**Comment by KomalPatel-github** [comment]
oh dear indeed!

**Comment by Masssly** [comment]
This should be fun! But looking at the time...

**Comment by notconfusing** [comment]
@Komchi I assigned this to myself, but if you want to take a shot at designing and then @fsoong can give you input I think that's a good use of time. 
@Masssly ''It is allowed to reuse resources produced before the competition starts, i.e. you do not have to start from scratch."

So maybe a good way to do this is to take one or more of the graphics that has already been made in the original paper, and then use the same data, but redesign the style and arrange a few together so that it tells a more compelling story. I think the best ones would be %-female by date of birth, and the world map. But I give you creative leeway.

**Comment by fsoong** [comment]
Sounds like a good plan. I'm planning to share with Komchi some online
tutorials for information design basics and designing landing pages in
photoshop. Infographic tutorials tend to be more print-based, which would
be less translatable to our main data viz / dashboard project :)

On Mon, May 18, 2015 at 3:17 PM, Max Klein notifications@github.com wrote:

> @Komchi https://github.com/Komchi I assigned this to myself, but if you
> want to take a shot at designing and then @fsoong
> https://github.com/fsoong can give you input I think that's a good use
> of time.
> @Masssly https://github.com/Masssly ''It is allowed to reuse resources
> produced before the competition starts, i.e. you do not have to start from
> scratch."
> 
> So maybe a good way to do this is to take one or more of the graphics that
> has already been made in the original paper, and then use the same data,
> but redesign the style and arrange a few together so that it tells a more
> compelling story. I think the best ones would be %-female by date of birth,
> and the world map. But I give you creative leeway.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/notconfusing/WIGI/issues/19#issuecomment-103231145.

## 

Frances Soong
Visual UX Designer
(908) 635-1534
francessoong.com http://www.francessoong.com/
LinkedIn https://www.linkedin.com/in/francessoong | Twitter
https://www.linkedin.com/in/francessoong

**Comment by KomalPatel-github** [comment]
Yeah I would love to give it a try.

**Comment by Masssly** [comment]
@notconfusing I am looking at how we can arouse and keep the interest of the jury for a while. The "world map" and "female percentage of biographies by culture" seem more related than the "world map" and "%-female by date of birth".
Do you have a reason why you chose the latter? 
:thought_balloon: Also, I haven't graphed but I can imagine how kindling " female percentage of biographies" by "culture" by "date (era) of birth" will be.
BTW where can I find the interactive version of the world map?

**Comment by notconfusing** [comment]
I think they're all good candidates if they got a face lift and were weaved
into an info graphic.

**Comment by fsoong** [comment]
Hi All, I spoke with with Komchi over video chat this past Wednesday and suggested he work with Max with daily syncs or 3-5 times a week check-ins. Like over email as he had done with me and others for the initial project. I shared with him quite a few resources, but am editing my list (I'm wary of there being too many resources out there and want to make sure I pick out good ones for good reasons.) I will post these later today. For now everyone should review what an infographic is on Wikipedia at the very least: https://en.wikipedia.org/wiki/Infographic. Note it's part of a series for "Data Visualization" that you can link to using the righthand navigation. The WIGI project is an "interactive data visualization."

I told Komchi, he and Max should plan two review sessions for Masssly and I to attend and give feedback. The first in-progress review sometime this Sunday and a final review next Friday. That way you have plenty of time to take in our feedback and preparing the final submissions before June 1st.

**Comment by fsoong** [comment]
Okay, to start with what is an infographic and how to make a good one is to know there are many, many bad ones. I start with posts by Column Five, one of most well-known agencies creating the prettiest infographics you see going viral today (including almost all the ones used on http://good.is).
- "What Makes a Good Infographic?" http://www.columnfivemedia.com/makes-good-infographic
- "Crafting an Infographic Narrative" http://www.columnfivemedia.com/crafting-an-infographic-narrative
- "The Most Important Piece of an Infographic" http://www.columnfivemedia.com/important-piece-infographic
- A pretty video summing why infographics are valuable: https://vimeo.com/29684853

Any of the other ColumFive blog posts are recommended too. I do not recommend following most of the guides you find by immediately Googling. Since Column Five is an agency selling infographics, they don't provided as much information on how to make them, but many people who create infographics are even worse—selling you ads. 

Next, Information Design 101— the foundation of infographics and data visualization
- From Mapping Complex Information: https://sheilapontis.wordpress.com/2010/09/23/information-design-basics-and-essentials/

But you can read and learn all the basics without being able to produce anything of that level. To achieve that requires practice. Here are some using Photoshop, but I can dig up some tutorials for Sketch if need be.
- Nobody tells this to beginners: the only prerequisite is good taste https://www.youtube.com/watch?v=E1oZhEIrer4 (watch this when you become discouraged)
- Design a Gratitude Log Landing page using Photoshop http://webdesign.tutsplus.com/tutorials/design-an-elegant-gratitude-log-landing-page-with-photoshop--cms-22787 (Easy exercise anyone can learn, very general not trend-specific)
- 6 Beginner “Safety First” Color Guidelines for the Web http://webdesign.tutsplus.com/tutorials/6-beginner-safety-first-color-guidelines-for-the-web--cms-21462 (Very fast guide geared for people without a natural knack or interest in color)

And other Photoshop tips form me:
- Design similar pages using layers in Photoshop (have the background be one layer, stack unique elements from each page on top)
- NEVER transform text (squish, skew, distort, or scale). Its disrespectful to the type designers intent and designs and you will confuse yourself when you try to copy that text later.

This is more for Komchi. Skillshare classes are of varying quality and are not all taught by experts, but are all fairly in-depth. Also some classes you learn how to critique and have your work critiqued.
- Try the excercises from this Skillshare class, Visual Narratives 101 http://www.skillshare.com/classes/design/The-Art-of-the-Story-Creating-Visual-Narratives/1893972902
- Apply for this scholarship too! http://www.skillshare.com/scholarships

More Advanced:
- A Guide to Creating Dashboards People Love to Use http://static1.squarespace.com/static/52f42657e4b0b3416ff6b831/t/5310292ce4b08d35a87c9426/1393568044420/Guide_to_Dashboard_Design.pdf
  (Hits a lot of stuff I’m teaching myself now: info from Tufte, Few, common functions, etc. and skims at skills I refined in college: fundamentals of color, type, grid, form, etc.)
- Google’s Web Fundamentals https://developers.google.com/web/fundamentals/?hl=en
  (Are geared more towards responsive design sensibilities, a lot of cool non-profit and data-viz tools still follow desktop web-only patterns as I suspect we will too.)

**Comment by notconfusing** [comment]
https://commons.wikimedia.org/wiki/File:WIGI_Infographic.png

**Comment by fsoong** [comment]
To others: please do not share on social media or publicly just yet! There are a few touches I'd like to work on still and add with Max. If you email to friends or family make sure they know it's a submitted draft :)

**Comment by Masssly** [comment]
@fsoong Can you do something about the fonts? See https://groups.google.com/forum/#!topic/wigi-project/HXiXSfCtaHE

**Comment by QEDK** [comment]
Convert the picture to .svg so that it doesn't lose quality and its size can be adjusted. :)

**Comment by fsoong** [comment]
I don't think I need to make the fonts larger or convert the picture to .svg. SVG is still not standardized format and renders different across different browsers. I've had infographics become unreadable in SVG. If anything, I want to explore making the text darker in certain areas.

It'd help me though if you guys could use MS paint to draw on the graphic and point at which areas seem too small or hard to read. Please post your comments in this new issue below. This issue is closed.

Polish Infographic for Social Media #22
